# -*- coding: utf-8 -*-
"""Tugas Akhir Analitik Teks IndoBERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wLV4zOJGdR4wiLhmRws4dubm71Tj0yhf
"""

!pip install -q transformers peft accelerate scikit-learn matplotlib pandas torch seaborn

import pandas as pd
import numpy as np
import torch
import re
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, ConfusionMatrixDisplay

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding
)

from peft import LoraConfig, get_peft_model, TaskType

df = pd.read_csv("/content/sample_data/TokopediaLocknLock.csv")
df = df.rename(columns={df.columns[0]: "text"})

print("Jumlah data mentah:", len(df))
df.head()

#Hapus data kosong & duplikat
df = df.dropna(subset=["text"])
df = df.drop_duplicates()

def clean_text(text):
    text = str(text).lower()                      # lowercase
    text = re.sub(r"http\S+", "", text)           # hapus URL
    text = re.sub(r"@\w+", "", text)              # hapus mention
    text = re.sub(r"#\w+", "", text)              # hapus hashtag
    text = re.sub(r"[^a-zA-Z\s]", "", text)       # hapus simbol & angka
    text = re.sub(r"\s+", " ", text).strip()      # hapus spasi berlebih
    return text

#Filtering teks terlalu pendek
df = df[df["text"].str.len() >= 5]

print("Jumlah data setelah preprocessing:", len(df))

# Simpan versi asli
df["raw_text"] = df["text"]

# Terapkan preprocessing ke kolom baru
df["clean_text"] = df["text"].astype(str).apply(clean_text)

# Membandingkan sebelum dan sesudah preprocessing
sample = df.sample(5, random_state=42)

for i, row in sample.iterrows():
    print("SEBELUM :", row["raw_text"])
    print("SESUDAH :", row["clean_text"])
    print("-" * 80)

#Pemberian Label
def label_sentiment(text):
    positive_words = ["bagus", "mantap","murah","baik","awet","bonus","terima kasih","amanah","promo","puas","gratis","cocok", "asli","keren","sesuai","cepat","senang","tebal","berguna","diskon","kualitas","rapi","kokoh", "manfaat","tahan","suka","langganan"]
    negative_words = ["jelek","tipis","bau","sobek","lecet","lambat","parah","debu","kotor","plastik", "rusak", "kecewa","cacat", "salah","buruk", "retak", "penyok","bocor","sampah", "sobek","pecah","tidak sesuai","hancur","mahal","tapi"]

    pos = sum(w in text for w in positive_words)
    neg = sum(w in text for w in negative_words)

    if pos > neg:
        return "positive"
    elif neg > pos:
        return "negative"
    else:
        return "neutral"

df["label"] = df["text"].apply(label_sentiment)

print("\nDistribusi label:")
print(df["label"].value_counts())
df["label"] = df["text"].apply(label_sentiment)
print("\nDistribusi label setelah optimasi:")
print(df["label"].value_counts(normalize=True) * 100)

le = LabelEncoder()
df["label_id"] = le.fit_transform(df["label"])

#Pembagian data untuk training, validation dan testing menjadi 70:15:15
texts = df["clean_text"]
labels = df["label"]

X_train, X_temp, y_train, y_temp = train_test_split(
    texts, labels,
    test_size=0.30,
    random_state=42,
    stratify=labels
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

train_texts = X_train
val_texts = X_val
test_texts = X_test

label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_val_encoded = label_encoder.transform(y_val)
y_test_encoded = label_encoder.transform(y_test)

label_map = {idx: label for idx, label in enumerate(label_encoder.classes_)}

# Assign encoded labels back to y_train, y_val, y_test for subsequent steps
y_train = y_train_encoded
y_val = y_val_encoded
y_test = y_test_encoded

print("\nJumlah data:")
print("Train:", len(train_texts))
print("Validation:", len(val_texts))
print("Test:", len(test_texts))

print("\nDistribusi label (encoded):")
print(pd.Series(y_train_encoded).value_counts())

#Tokenisasi indoBert
model_name = "indobenchmark/indobert-base-p1"
tokenizer = AutoTokenizer.from_pretrained(model_name)

train_enc = tokenizer(list(train_texts), truncation=True)
val_enc   = tokenizer(list(val_texts), truncation=True)
test_enc  = tokenizer(list(test_texts), truncation=True)

class ReviewDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels.tolist()

    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = ReviewDataset(train_enc, y_train)
val_dataset   = ReviewDataset(val_enc, y_val)
test_dataset  = ReviewDataset(test_enc, y_test)

#HHitung class weight
class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train),
    y=y_train
)

class_weights = torch.tensor(class_weights, dtype=torch.float)
print("Class weights:", class_weights)

#model + LoRA PEFT
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=len(le.classes_)
)

lora_config = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    r=8,
    lora_alpha=32,
    lora_dropout=0.1
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# CUSTOM TRAINER (WEIGHTED LOSS)
class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits
        loss_fn = torch.nn.CrossEntropyLoss(weight=class_weights.to(logits.device))
        loss = loss_fn(logits, labels)
        return (loss, outputs) if return_outputs else loss

# Training Arguments
training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=5,
    learning_rate=2e-5,
    logging_steps=50,
    save_strategy="no",
    report_to="none"
)

data_collator = DataCollatorWithPadding(tokenizer)

# Fungsi evaluasi
def compute_metrics(eval_pred):
    logits, labels = eval_pred.predictions, eval_pred.label_ids
    preds = np.argmax(logits, axis=-1)
    acc = accuracy_score(labels, preds)
    f1 = f1_score(labels, preds, average="weighted")
    return {"accuracy": acc, "f1": f1}

trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

trainer.train()

eval_results = trainer.evaluate()
print("\nEvaluation Results:", eval_results)

test_labels = test_labels.reset_index(drop=True)
test_texts  = test_texts.reset_index(drop=True)

test_dataset = ReviewDataset(
    encodings=test_enc,
    labels=test_labels
)

predictions = trainer.predict(test_dataset)
y_pred = np.argmax(predictions.predictions, axis=1)

# convert test_labels ke numpy array
y_true = test_labels.to_numpy() if isinstance(test_labels, pd.Series) else np.array(test_labels)

print(len(y_true), len(y_pred))  # harus sama

predictions = trainer.predict(test_dataset)
y_pred = np.argmax(predictions.predictions, axis=1)
y_true = test_labels.to_numpy() if isinstance(test_labels, pd.Series) else test_labels

cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=le.classes_)
disp.plot(cmap="Blues", values_format="d")
plt.title("Confusion Matrix IndoBERT + LoRA")
plt.show()

